name: Docker Latest

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
  pull_request:
    tags-ignore:
      - "*"
    branches-ignore:
      - "*"

jobs:
  push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 14-alpine
          - 16-alpine

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    name: Tag & Test Latest (node:${{ matrix.node }})

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build testing image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: localhost:5000/soketi/pws:latest-${{ matrix.node }}
          build-args: |
            VERSION=${{ matrix.node }}

      - name: Test
        run: |
          docker run -d -p 6001:6001 -e DEBUG=1 localhost:5000/soketi/pws:latest-${{ matrix.node }}
          sleep 5
          curl --silent -XGET --fail http://127.0.0.1:6001

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: quay.io/soketi/pws:latest-${{ matrix.node }}
          build-args: |
            VERSION=${{ matrix.node }}
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
